# Generated by Django 4.2.3 on 2023-07-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(default='https://loremflickr.com/320/320/plane', upload_to='plane_images'),
        ),
    ]
